version: 2.1

jobs:
    build_and_test:
        working_directory: ~/repo
        environment:
            VERSION: 0.0.1
        docker:
            - image: oddsocks/nanovdb:dev-base
              auth:
                username: $DOCKERHUB_USERNAME
                password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - run:
                name: build-gcc8
                command: |
                    ./ci/build_core.sh gcc8 g++-8 10.2 Release -DNANOVDB_USE_OPTIX=OFF -DNANOVDB_USE_CUDA=OFF
                    ./ci/test_core.sh gcc8
                    ./ci/test_render.sh gcc8
            - store_artifacts:
                path: ./test-results/testNanoVDB/gcc8.xml
            - store_artifacts:
                path: ./__output/gcc8/gold.0000.png
            - run:
                name: build-gcc6
                command: |
                    ./ci/build_core.sh gcc6 g++-6 10.2 Release -DNANOVDB_USE_OPTIX=OFF -DNANOVDB_USE_CUDA=OFF
                    ./ci/test_core.sh gcc6
                    ./ci/test_render.sh gcc6
            - store_artifacts:
                path: ./test-results/testNanoVDB/gcc6.xml
            - store_artifacts:
                path: ./__output/gcc6/gold.0000.png
            - run:
                name: build-clang
                command: |
                    ./ci/build_core.sh clang7 clang++ 10.2 Release -DNANOVDB_USE_OPTIX=OFF -DNANOVDB_USE_CUDA=OFF
                    ./ci/test_core.sh clang7
                    ./ci/test_render.sh clang7
            - store_artifacts:
                path: ./test-results/testNanoVDB/clang7.xml
            - store_artifacts:
                path: ./__output/clang7/gold.0000.png
            - run:
                name: build-msvc
                command: |
                    ./ci/build_core.sh msvc16 msvc 10.2 Release -DNANOVDB_USE_OPENVDB=OFF -DNANOVDB_USE_TBB=OFF -DNANOVDB_USE_ZLIB=OFF -DNANOVDB_USE_BLOSC=OFF -DNANOVDB_BUILD_TOOLS=ON -DNANOVDB_BUILD_UNITTESTS=OFF -DNANOVDB_USE_OPTIX=OFF -DNANOVDB_USE_CUDA=OFF
            - store_test_results:
                path: test-results
workflows:
    build_and_test:
        jobs:
            - build_and_test
            
           